---
name: Lint

on:
  pull_request:
  push:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@9bfd0452ce630f6469986587db7f0feab5b22273 # v3.5.0
        with:
          files: .
          config_file: .markdownlint.yaml
          dot: true

      - name: typos-action spellchecker
        uses: crate-ci/typos@f244a2b9ce610dd507d98a902c3b9aca7a050a90 # v1.42.1

      - name: yamllint
        uses: ibiqlik/action-yamllint@2576378a8e339169678f9939646ee3ee325e845c # v3.1.1

      - name: commitlint
        uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6
